// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProvaPub.Repository;

#nullable disable

namespace ProvaPub.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20250815221955_primary-key")]
    partial class primarykey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProvaPub.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Robyn Tillman"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Iris Lakin"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Roberto Kulas"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Claude Cummerata"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Roosevelt MacGyver"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Leigh Batz"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Wilma Halvorson"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Alicia Rutherford"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Clyde Quigley"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Leon Hintz"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Della O'Connell"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Eunice Cremin"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Nicholas O'Hara"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Patty Bashirian"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Hilda Farrell"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Patrick Runte"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Ernesto Carter"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Becky Nicolas"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Winifred Lind"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Gail Buckridge"
                        });
                });

            modelBuilder.Entity("ProvaPub.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ProvaPub.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Generic Frozen Computer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Intelligent Granite Tuna"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Handmade Cotton Chicken"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Practical Rubber Fish"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Awesome Fresh Shirt"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Awesome Cotton Salad"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Gorgeous Soft Salad"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Awesome Granite Bike"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Small Cotton Towels"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Handmade Granite Bacon"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Sleek Concrete Shoes"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Practical Plastic Chicken"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Gorgeous Frozen Chicken"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Handcrafted Granite Shirt"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Rustic Fresh Cheese"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Generic Wooden Pants"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Practical Soft Shoes"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Incredible Soft Soap"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Unbranded Granite Cheese"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Refined Steel Bacon"
                        });
                });

            modelBuilder.Entity("ProvaPub.Models.RandomNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Numbers");
                });

            modelBuilder.Entity("ProvaPub.Models.Order", b =>
                {
                    b.HasOne("ProvaPub.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ProvaPub.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
